Add google search
mordechairoth/IveltChromeExtension pull request #34
Opened 2021-07-19 23:41 UTC by mayim-chayim

@kavhayushar please review

2021-07-20 03:55 UTC, kavhayushar requested changes
Seems to have an issue with doing a second search.
The issue is with the {{value}} replace functionality which is being replaced on the first search and no longer found on the second search.
Therefore I suggest to concat the search term when hitting the search.
See inline comments.

2021-07-20 03:55 UTC, kavhayushar commented on extension/js/addGoogleSearch.js
> +        let topicTitle = document.querySelectorAll('.topic-title > a')[0].text;
I would move down the searchUrl declaration after the topicTtile, and change it to hardcode the title. (and remove the {{value}} placeholder.
`let searchUrl = 'https://www.google.com/search?q=site%3Aivelt.com+intitle%3A"' + topicTitle + '"'`

2021-07-20 03:55 UTC, kavhayushar commented on extension/js/addGoogleSearch.js
> +                searchUrl = searchUrl.replace('{{title}}',topicTitle)
Remove this line as it is already hardcoded.

2021-07-20 03:55 UTC, kavhayushar commented on extension/js/addGoogleSearch.js
> +                searchUrl = searchUrl.replace('{{value}}',document.getElementById('g_search_keywords').value)
Remove this line as we are going to append it to the URL parameter below.

2021-07-20 03:55 UTC, kavhayushar commented on extension/js/addGoogleSearch.js
> +                window.open(searchUrl, '_blank').focus();
Add search term to the URL parameter (or if you prefer for clarity, we can save it to a variable and pass it along here.)
`window.open(searchUrl + "+" + document.getElementById("g_search_keywords").value, '_blank').focus();`

2021-07-20 03:56 UTC, kavhayushar commented
All in all, nice job. I would append the changes myself but I have no access to your branch, hence no access to modify the PR.

2021-07-20 18:01 UTC, kavhayushar approved these changes
Works great. Thank you for your work.
Please send an invoice. 😂

2021-07-20 18:28 UTC, merged

2021-07-21 03:34 UTC, KnaperYaden commented
@mayim-chayim this is only Google Search "in thread".

Can you do the same idea as a main ivelt search. Something like this:
![image](https://user-images.githubusercontent.com/87161728/126426522-0fcf80d1-b8af-4d96-9bf6-64c8df95d254.png)

(Also Google is usually spelled as גוגל, not גאאגל.)

2021-07-22 16:36 UTC, mayim-chayim commented
> @mayim-chayim this is only Google Search "in thread".
> 
> Can you do the same idea as a main ivelt search. Something like this:

I don't think that it is so important, because you can always do a `site:ivelt.com`, to search in a thread you need an additional `intitle`, with the RTL issues adding confusion 
maybe one day I will do it
> (Also Google is usually spelled as גוגל, not גאאגל.)

Changed

2021-07-22 16:59 UTC, KnaperYaden commented
> I don't think that it is so important, because you can always do a `site:ivelt.com`, to search in a thread you need an additional `intitle`, with the RTL issues adding confusion

Correct, but whole site search is probably needed more often (or maybe just by me...)